// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score.proto

package com.acdp.grpc;

public final class Score {
  private Score() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScoreRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ScoreRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 ballNumber = 1;</code>
     * @return The ballNumber.
     */
    int getBallNumber();

    /**
     * <code>int32 runsScored = 2;</code>
     * @return The runsScored.
     */
    int getRunsScored();
  }
  /**
   * Protobuf type {@code ScoreRequest}
   */
  public  static final class ScoreRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ScoreRequest)
      ScoreRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScoreRequest.newBuilder() to construct.
    private ScoreRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScoreRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScoreRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScoreRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ballNumber_ = input.readInt32();
              break;
            }
            case 16: {

              runsScored_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acdp.grpc.Score.internal_static_ScoreRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acdp.grpc.Score.internal_static_ScoreRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acdp.grpc.Score.ScoreRequest.class, com.acdp.grpc.Score.ScoreRequest.Builder.class);
    }

    public static final int BALLNUMBER_FIELD_NUMBER = 1;
    private int ballNumber_;
    /**
     * <code>int32 ballNumber = 1;</code>
     * @return The ballNumber.
     */
    public int getBallNumber() {
      return ballNumber_;
    }

    public static final int RUNSSCORED_FIELD_NUMBER = 2;
    private int runsScored_;
    /**
     * <code>int32 runsScored = 2;</code>
     * @return The runsScored.
     */
    public int getRunsScored() {
      return runsScored_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ballNumber_ != 0) {
        output.writeInt32(1, ballNumber_);
      }
      if (runsScored_ != 0) {
        output.writeInt32(2, runsScored_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ballNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ballNumber_);
      }
      if (runsScored_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, runsScored_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.acdp.grpc.Score.ScoreRequest)) {
        return super.equals(obj);
      }
      com.acdp.grpc.Score.ScoreRequest other = (com.acdp.grpc.Score.ScoreRequest) obj;

      if (getBallNumber()
          != other.getBallNumber()) return false;
      if (getRunsScored()
          != other.getRunsScored()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BALLNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getBallNumber();
      hash = (37 * hash) + RUNSSCORED_FIELD_NUMBER;
      hash = (53 * hash) + getRunsScored();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.acdp.grpc.Score.ScoreRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.acdp.grpc.Score.ScoreRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.acdp.grpc.Score.ScoreRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.acdp.grpc.Score.ScoreRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.acdp.grpc.Score.ScoreRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.acdp.grpc.Score.ScoreRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.acdp.grpc.Score.ScoreRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.acdp.grpc.Score.ScoreRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.acdp.grpc.Score.ScoreRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.acdp.grpc.Score.ScoreRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.acdp.grpc.Score.ScoreRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.acdp.grpc.Score.ScoreRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.acdp.grpc.Score.ScoreRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ScoreRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ScoreRequest)
        com.acdp.grpc.Score.ScoreRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.acdp.grpc.Score.internal_static_ScoreRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.acdp.grpc.Score.internal_static_ScoreRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.acdp.grpc.Score.ScoreRequest.class, com.acdp.grpc.Score.ScoreRequest.Builder.class);
      }

      // Construct using com.acdp.grpc.Score.ScoreRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ballNumber_ = 0;

        runsScored_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.acdp.grpc.Score.internal_static_ScoreRequest_descriptor;
      }

      @java.lang.Override
      public com.acdp.grpc.Score.ScoreRequest getDefaultInstanceForType() {
        return com.acdp.grpc.Score.ScoreRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.acdp.grpc.Score.ScoreRequest build() {
        com.acdp.grpc.Score.ScoreRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.acdp.grpc.Score.ScoreRequest buildPartial() {
        com.acdp.grpc.Score.ScoreRequest result = new com.acdp.grpc.Score.ScoreRequest(this);
        result.ballNumber_ = ballNumber_;
        result.runsScored_ = runsScored_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.acdp.grpc.Score.ScoreRequest) {
          return mergeFrom((com.acdp.grpc.Score.ScoreRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.acdp.grpc.Score.ScoreRequest other) {
        if (other == com.acdp.grpc.Score.ScoreRequest.getDefaultInstance()) return this;
        if (other.getBallNumber() != 0) {
          setBallNumber(other.getBallNumber());
        }
        if (other.getRunsScored() != 0) {
          setRunsScored(other.getRunsScored());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.acdp.grpc.Score.ScoreRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.acdp.grpc.Score.ScoreRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int ballNumber_ ;
      /**
       * <code>int32 ballNumber = 1;</code>
       * @return The ballNumber.
       */
      public int getBallNumber() {
        return ballNumber_;
      }
      /**
       * <code>int32 ballNumber = 1;</code>
       * @param value The ballNumber to set.
       * @return This builder for chaining.
       */
      public Builder setBallNumber(int value) {
        
        ballNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ballNumber = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBallNumber() {
        
        ballNumber_ = 0;
        onChanged();
        return this;
      }

      private int runsScored_ ;
      /**
       * <code>int32 runsScored = 2;</code>
       * @return The runsScored.
       */
      public int getRunsScored() {
        return runsScored_;
      }
      /**
       * <code>int32 runsScored = 2;</code>
       * @param value The runsScored to set.
       * @return This builder for chaining.
       */
      public Builder setRunsScored(int value) {
        
        runsScored_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 runsScored = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRunsScored() {
        
        runsScored_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ScoreRequest)
    }

    // @@protoc_insertion_point(class_scope:ScoreRequest)
    private static final com.acdp.grpc.Score.ScoreRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.acdp.grpc.Score.ScoreRequest();
    }

    public static com.acdp.grpc.Score.ScoreRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScoreRequest>
        PARSER = new com.google.protobuf.AbstractParser<ScoreRequest>() {
      @java.lang.Override
      public ScoreRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScoreRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScoreRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScoreRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.acdp.grpc.Score.ScoreRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScoreResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ScoreResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 runsToWin = 1;</code>
     * @return The runsToWin.
     */
    int getRunsToWin();

    /**
     * <code>int32 remainingBalls = 2;</code>
     * @return The remainingBalls.
     */
    int getRemainingBalls();

    /**
     * <code>double requiredRunRate = 3;</code>
     * @return The requiredRunRate.
     */
    double getRequiredRunRate();
  }
  /**
   * Protobuf type {@code ScoreResponse}
   */
  public  static final class ScoreResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ScoreResponse)
      ScoreResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScoreResponse.newBuilder() to construct.
    private ScoreResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScoreResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScoreResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScoreResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              runsToWin_ = input.readInt32();
              break;
            }
            case 16: {

              remainingBalls_ = input.readInt32();
              break;
            }
            case 25: {

              requiredRunRate_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acdp.grpc.Score.internal_static_ScoreResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acdp.grpc.Score.internal_static_ScoreResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acdp.grpc.Score.ScoreResponse.class, com.acdp.grpc.Score.ScoreResponse.Builder.class);
    }

    public static final int RUNSTOWIN_FIELD_NUMBER = 1;
    private int runsToWin_;
    /**
     * <code>int32 runsToWin = 1;</code>
     * @return The runsToWin.
     */
    public int getRunsToWin() {
      return runsToWin_;
    }

    public static final int REMAININGBALLS_FIELD_NUMBER = 2;
    private int remainingBalls_;
    /**
     * <code>int32 remainingBalls = 2;</code>
     * @return The remainingBalls.
     */
    public int getRemainingBalls() {
      return remainingBalls_;
    }

    public static final int REQUIREDRUNRATE_FIELD_NUMBER = 3;
    private double requiredRunRate_;
    /**
     * <code>double requiredRunRate = 3;</code>
     * @return The requiredRunRate.
     */
    public double getRequiredRunRate() {
      return requiredRunRate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (runsToWin_ != 0) {
        output.writeInt32(1, runsToWin_);
      }
      if (remainingBalls_ != 0) {
        output.writeInt32(2, remainingBalls_);
      }
      if (requiredRunRate_ != 0D) {
        output.writeDouble(3, requiredRunRate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (runsToWin_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, runsToWin_);
      }
      if (remainingBalls_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, remainingBalls_);
      }
      if (requiredRunRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, requiredRunRate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.acdp.grpc.Score.ScoreResponse)) {
        return super.equals(obj);
      }
      com.acdp.grpc.Score.ScoreResponse other = (com.acdp.grpc.Score.ScoreResponse) obj;

      if (getRunsToWin()
          != other.getRunsToWin()) return false;
      if (getRemainingBalls()
          != other.getRemainingBalls()) return false;
      if (java.lang.Double.doubleToLongBits(getRequiredRunRate())
          != java.lang.Double.doubleToLongBits(
              other.getRequiredRunRate())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RUNSTOWIN_FIELD_NUMBER;
      hash = (53 * hash) + getRunsToWin();
      hash = (37 * hash) + REMAININGBALLS_FIELD_NUMBER;
      hash = (53 * hash) + getRemainingBalls();
      hash = (37 * hash) + REQUIREDRUNRATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRequiredRunRate()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.acdp.grpc.Score.ScoreResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.acdp.grpc.Score.ScoreResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.acdp.grpc.Score.ScoreResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.acdp.grpc.Score.ScoreResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.acdp.grpc.Score.ScoreResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.acdp.grpc.Score.ScoreResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.acdp.grpc.Score.ScoreResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.acdp.grpc.Score.ScoreResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.acdp.grpc.Score.ScoreResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.acdp.grpc.Score.ScoreResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.acdp.grpc.Score.ScoreResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.acdp.grpc.Score.ScoreResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.acdp.grpc.Score.ScoreResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ScoreResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ScoreResponse)
        com.acdp.grpc.Score.ScoreResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.acdp.grpc.Score.internal_static_ScoreResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.acdp.grpc.Score.internal_static_ScoreResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.acdp.grpc.Score.ScoreResponse.class, com.acdp.grpc.Score.ScoreResponse.Builder.class);
      }

      // Construct using com.acdp.grpc.Score.ScoreResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        runsToWin_ = 0;

        remainingBalls_ = 0;

        requiredRunRate_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.acdp.grpc.Score.internal_static_ScoreResponse_descriptor;
      }

      @java.lang.Override
      public com.acdp.grpc.Score.ScoreResponse getDefaultInstanceForType() {
        return com.acdp.grpc.Score.ScoreResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.acdp.grpc.Score.ScoreResponse build() {
        com.acdp.grpc.Score.ScoreResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.acdp.grpc.Score.ScoreResponse buildPartial() {
        com.acdp.grpc.Score.ScoreResponse result = new com.acdp.grpc.Score.ScoreResponse(this);
        result.runsToWin_ = runsToWin_;
        result.remainingBalls_ = remainingBalls_;
        result.requiredRunRate_ = requiredRunRate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.acdp.grpc.Score.ScoreResponse) {
          return mergeFrom((com.acdp.grpc.Score.ScoreResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.acdp.grpc.Score.ScoreResponse other) {
        if (other == com.acdp.grpc.Score.ScoreResponse.getDefaultInstance()) return this;
        if (other.getRunsToWin() != 0) {
          setRunsToWin(other.getRunsToWin());
        }
        if (other.getRemainingBalls() != 0) {
          setRemainingBalls(other.getRemainingBalls());
        }
        if (other.getRequiredRunRate() != 0D) {
          setRequiredRunRate(other.getRequiredRunRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.acdp.grpc.Score.ScoreResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.acdp.grpc.Score.ScoreResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int runsToWin_ ;
      /**
       * <code>int32 runsToWin = 1;</code>
       * @return The runsToWin.
       */
      public int getRunsToWin() {
        return runsToWin_;
      }
      /**
       * <code>int32 runsToWin = 1;</code>
       * @param value The runsToWin to set.
       * @return This builder for chaining.
       */
      public Builder setRunsToWin(int value) {
        
        runsToWin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 runsToWin = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRunsToWin() {
        
        runsToWin_ = 0;
        onChanged();
        return this;
      }

      private int remainingBalls_ ;
      /**
       * <code>int32 remainingBalls = 2;</code>
       * @return The remainingBalls.
       */
      public int getRemainingBalls() {
        return remainingBalls_;
      }
      /**
       * <code>int32 remainingBalls = 2;</code>
       * @param value The remainingBalls to set.
       * @return This builder for chaining.
       */
      public Builder setRemainingBalls(int value) {
        
        remainingBalls_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 remainingBalls = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemainingBalls() {
        
        remainingBalls_ = 0;
        onChanged();
        return this;
      }

      private double requiredRunRate_ ;
      /**
       * <code>double requiredRunRate = 3;</code>
       * @return The requiredRunRate.
       */
      public double getRequiredRunRate() {
        return requiredRunRate_;
      }
      /**
       * <code>double requiredRunRate = 3;</code>
       * @param value The requiredRunRate to set.
       * @return This builder for chaining.
       */
      public Builder setRequiredRunRate(double value) {
        
        requiredRunRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double requiredRunRate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequiredRunRate() {
        
        requiredRunRate_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ScoreResponse)
    }

    // @@protoc_insertion_point(class_scope:ScoreResponse)
    private static final com.acdp.grpc.Score.ScoreResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.acdp.grpc.Score.ScoreResponse();
    }

    public static com.acdp.grpc.Score.ScoreResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScoreResponse>
        PARSER = new com.google.protobuf.AbstractParser<ScoreResponse>() {
      @java.lang.Override
      public ScoreResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScoreResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScoreResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScoreResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.acdp.grpc.Score.ScoreResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ScoreRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ScoreRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ScoreResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ScoreResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013score.proto\"6\n\014ScoreRequest\022\022\n\nballNum" +
      "ber\030\001 \001(\005\022\022\n\nrunsScored\030\002 \001(\005\"S\n\rScoreRe" +
      "sponse\022\021\n\trunsToWin\030\001 \001(\005\022\026\n\016remainingBa" +
      "lls\030\002 \001(\005\022\027\n\017requiredRunRate\030\003 \001(\00125\n\005sc" +
      "ore\022,\n\007scoring\022\r.ScoreRequest\032\016.ScoreRes" +
      "ponse(\0010\001B\017\n\rcom.acdp.grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ScoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ScoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ScoreRequest_descriptor,
        new java.lang.String[] { "BallNumber", "RunsScored", });
    internal_static_ScoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ScoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ScoreResponse_descriptor,
        new java.lang.String[] { "RunsToWin", "RemainingBalls", "RequiredRunRate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
